batch_size: 8
dataset_name: null
dataset_config_name: null
train_file: /mnt/storage/Documents/hugging_face/repos_all/metadata/tests/data/train_toy_wikitext.jsonl
validation_file: /mnt/storage/Documents/hugging_face/repos_all/metadata/tests/data/val_toy_wikitext.jsonl
overwrite_cache: false
cache_dir: null
preprocessing_num_workers: null
validation_split_percentage: 5
block_size: 100