metadata_config:
  metadata_list:
  - html
  local_metadata_special_tokens:
    html: htmlOn
  metadata_sep: ' | '
  metadata_key_value_sep: ': '
  metadata_probability: 0.5
  treat_local_metadata_as_regular_text: true
  add_local_metadata_special_tokens_in_prefix: true
  metadata_prefix_sep: ' |||'
  metadata_prefix_start_seq: ' '
  max_seq_len: 1024
  html_parser_config:
    all_tags_rules:
      attributes_to_keep:
      - class
      - id
      txt_max_chr_len: 0
      txt_min_chr_len: 0
      tags_exceptions_to_txt_max_min_chr_len: []
    tags_to_remove_alone_tag_name:
    - body
    tags_to_remove_alone_txt_max_chr_len:
    - .inf
    tags_to_remove_alone_txt_min_chr_len:
    - 0.0
experiment: with_metadata
per_device_eval_batch_size: 3
per_device_train_batch_size: 3
dataset_name: "bs-modeling-metadata/c4-en-html-with-metadata"
dataset_config_name: null
train_file: "c4-en-html_cc-main-2019-18_pq10-262.jsonl.gz"
validation_file: "c4-en-html_cc-main-2019-18_pq10-263.jsonl.gz"
overwrite_cache: false
cache_dir: null
extension: null
preprocessing_num_workers: 8
validation_split_percentage: null
block_size: null
map_batch_size: 1