data_config:
  validation_size_max: null
  metadata_config:
    random_sample_metadata: false
    metadata_list:
    - html
    - entity
    - timestamp
    - website_description
    - title
    - url
    - datasource
    - length
    - entity_paragraph
    metadata_column_list:
    - html
    - entity
    - timestamp
    - website_desc
    - title
    - url
    - generation_datasource
    - generation_length_sentence
    - generation_length_text
    - entity_paragraph
    local_metadata_special_tokens: null
    metadata_sep: ' | '
    metadata_key_value_sep: ': '
    metadata_probability: 1.0
    treat_local_metadata_as_regular_text: true
    add_local_metadata_special_tokens_in_prefix: true
    metadata_prefix_sep: ' |||'
    metadata_prefix_start_seq: ''
    max_seq_len: 1024
    html_parser_config:
      all_tags_rules:
        attributes_to_keep:
        - class
        - id
        txt_max_chr_len: 0
        txt_min_chr_len: -.inf
        tags_exceptions_to_txt_max_min_chr_len: null
      tags_to_remove_alone_tag_name:
      - body
      tags_to_remove_alone_txt_max_chr_len:
      - .inf
      tags_to_remove_alone_txt_min_chr_len:
      - 0.0
  experiment: with_metadata_datasetv2
  per_device_eval_batch_size: 4
  per_device_train_batch_size: 4
  dataset_name: bs-modeling-metadata/c4-en-html-with-metadata
  dataset_config_name: null
  train_file: c4-en-html_cc-main-2019-18_pq00-001.jsonl.gz
  validation_file: c4-en-html_cc-main-2019-18_pq00-000.jsonl.gz
  overwrite_cache: false
  cache_dir: null
  extension: null
  preprocessing_num_workers: 6
  validation_split_percentage: 5
  block_size: null
  map_batch_size: 1
weight_decay: 0.01
learning_rate: 5.0e-05
gradient_accumulation_steps: 8
num_train_epochs: 1
max_train_steps: 100
lr_scheduler_type: linear
num_warmup_steps: 6
seed: 42
out_dir: metadata_outputs/
model_name: gpt2
project_name: metadata_lm
jobid: ''
start_with_eval: false
extra_steps_to_eval_save_at:
- 2
evaluation_strategy: STEPS
eval_num_per_epoch: 3
eval_steps: 20
save_strategy: STEPS
save_num_per_epoch: 3
save_steps: 5900
do_train: true
do_eval: true
gradient_checkpointing: true
