per_device_eval_batch_size: 2
per_device_train_batch_size: 2
weight_decay: 0.0
learning_rate: 5.0e-05
gradient_accumulation_steps: 1
num_train_epochs: 1
max_train_steps: 4
lr_scheduler_type: linear
num_warmup_steps: 1000
seed: 42
out_dir: output_dir
num_eval: 3